### ISSUE TITLE
Most commands not working

### ISSUE THREAD

**Issue by LoricAndre** [amirrezaask/fuzzy.nvim#1] opened 2020-10-25 00:04 UTC
Hi, thanks for the plugin. I've been looking for a lightweight alternative to fzf for quite some time now, and your plugin looks promising. 
I installed your plugin with vim-plug and I'm having a weird issue : The only working commad is `File`, the others display the floating window properly (apart from buffer, I elaborate more in my other issue), but then when I select an entry, the corresponding location seems to be opening in the preview window right before it closes instead of the main window.
Tell me if you want any more details or if I can generate a log somehow !

**Comment by amirrezaask** [comment] 2020-10-25 00:22
Hey thanks for installing. I was trying to have a fallback option to fzf so i changed some code, apart from Files and Grep command all the commands rely on fzf. Let me do a change and please report to me if the problem is solved

**Comment by amirrezaask** [comment] 2020-10-25 00:25
Please pull latest change, I have set it to by default always use the lua backend that needs no dependency.

**Comment by LoricAndre** [comment] 2020-10-25 09:07
I pulled the changed, nothing changed, it's still opening the files in the preview window.
[EDIT: I'm an idiot, it works now.]

**Comment by amirrezaask** [comment] 2020-10-25 09:48
Cool 👌👌👌 so I close this issue.

**Closed as completed by amirrezaask** 2020-10-25 09:48 UTC
